@BASE=http://127.0.0.1:8000

### Criar usuário
POST {{BASE}}/users
Content-Type: application/json
Accept: application/json

{
  "name": "Gabriel",
  "email": "gabriel@teste.com",
  "cell_phone": "11987654321",
  "password": "Teste123"
}